url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "29next App Design System" # the name of your site, e.g. ACME Corp.

# Build settings
source: ./docs
markdown: kramdown
permalink: pretty
highlighter: rouge

kramdown:
  input: GFM
sass:
    load_paths:
      - ../src/scss
      - _sass/
    style: compressed


exclude:
  - _sass

# Setup pattern collection
# collections:
#   patterns:
#     output: true
